version: '3.1'
services:
  bootapp:
    image: 8458882343/bootcampdevops:working
    ports:
      - '8081:8080'
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_USER: hello
      MYSQL_PASSWORD: hello
    volumes:
      - "mysql_data:/var/lib/mysql"

volumes:
  mysql_data: